### ISSUE TITLE
Dose and Units for PRESCRIBING table

### ISSUE THREAD

**Issue by smerek** [CDMFORUM/CDM-ERRATA#12]
A network raised the issue that there are no fields in the PRESCRIBING table (CDM v3.0) for "dose" and "units."

Issue is created for future assessment of feasibility and harmonization of adding this data to the PRESCRIBING table.

Network was encouraged to include this data in their localized implementation of CDM, per guiding principle #8.

**Comment by rusincovitch** [comment]
Because this is not an errata, merged with https://github.com/CDMFORUM/CDM-GUIDANCE/issues/4
