### ISSUE TITLE
PX_TYPE categorical value description

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-ERRATA#14]
In the PROCEDURES table, the PX_TYPE field contain categorical values.

To increase clarity and accuracy, the following modification to the categorical description is recommended:

"C4=CPT-4 (i.e., HCPCS Level I)"
updated to 
"C4=CPT Category I (also known as HCPCS Level I)"

**Comment by indera** [comment]
I would add that the "Definition/Comments" section for PX_TYPE can be improved by specifying the expected/known lengths of the corresponding PX codes:

ICD-9-CM (09) :  3-4 numbers
ICD-10-PCS (10): 7 alphanumeric characters 
CPT/HCPCS (C2/C3/C4/HC/H3): 5 alphanumeric characters (longer if modifiers are included -- should CDM be more specific about this?)

**Comment by rusincovitch** [comment]
@indera, thank you for your comments and suggestion! Given that this is a potential enhancement to the model, I'm going to move this ticket content to the guidance issue tracker.

**Comment by rusincovitch** [comment]
Merged with https://github.com/CDMFORUM/CDM-GUIDANCE/issues/20
