### ISSUE TITLE
Multiple DRG values possible for an encounter

### ISSUE THREAD

**Issue by baileych** [CDMFORUM/CDM-ERRATA#15]
It appears that, for better or worse, some health systems in PEDSnet assign more than one DRG value to a given admission (e.g. using different methods).  However, it's only possible to insert one value into a row as defined by the primary key (`patid`, `admit_date`, `providerid`, `enc_type`).  How would you like to handle this?  I'm guessing that the benefit derived from multiple DRG values is less than the burden of duplicating rows, so for now we're choosing one value and discarding the other(s).

Thanks!

**Comment by rusincovitch** [comment]
Merged with https://github.com/CDMFORUM/CDM-GUIDANCE/issues/21
