### ISSUE TITLE
PRESCRIBING.RAW_RX_MED_NAME clarification (if no CUI or Medication Name present)

### ISSUE THREAD

**Issue by indera** [CDMFORUM/CDM-ERRATA#16]
The CDM page 68 indicates in the "Additional Notes" section that "If a medication cannot be mapped it should still be present".

My interpretation of this sentence is along the lines of "If the EHR is not collecting CUIs they at least should collect the medication name, otherwise the table is not useful, but at the same time CDM cannot make the CUI a required field."

This is a bit confusing since of the four cases possible 
1. Medication name only (most of the time from a proprietary database)
2. CUI only
3. Medication name and CUI
4. No medication name and no CUI

it is not clear if we should even store a row in case 4 (no medication and no CUI).

Proposed change to the specification: If the RAW_RX_MED_NAME and RAW_RXNORM_CUI fields are empty in the source data then the row should not be stored.

**Comment by rusincovitch** [comment]
@indera, a challenge is that not all source medications may be cleanly mapped to a given CUI (reference: @smerek 's work [here](https://github.com/CDMFORUM/CDM-GUIDANCE/blob/master/2016-03-23%20PCORnetLabMappingCRI_2016_FINAL.pdf)).

I might guess that your proposed change to the spec may be driven by a use case which is completely based on availability for analysis? But another potential use case is to allow assessment of proportions of med records unable to be mapped (and especially given that these unanalyzable medication records could be impactful to analysis results). This is still an area under development, and I might expect that current work in data characterization development for this domain will give us insight about current data partner experiences in acquiring/transforming these data.

**Comment by indera** [comment]
@rusincovitch, thank you for the explanation -- now I understand that CDM needs to cover the "missing" data scenarios which would serve as a basis for further improvements.
I think you could close/mark invalid this item as you consider appropriate.

**Comment by rusincovitch** [comment]
This item has been incorporated into draft v3.0 Implementation Guidance, part of the PCORnet-wide open feedback cycle on Data Characterization (September 19-30, 2016): [https://pcornet.imeetcentral.com/p/aQAAAAAC1YDb](https://pcornet.imeetcentral.com/p/aQAAAAAC1YDb)
