### ISSUE TITLE
PDX = P for EI encounters?

### ISSUE THREAD

**Issue by dckc** [CDMFORUM/CDM-ERRATA#19]
Documentation for the PDX field of DIAGNOSIS says:

> Principal discharge diagnosis flag. Relevant only on IP and IS encounters.

but then _Table IVE. Principal Diagnoses for Institutional Encounters_ in the EDC report has a row for EI.

Is PDX actually relevant to EI as well as IP and IS?

**Comment by smerek** [comment]
Hi Dan.
Good catch!  Yes, PDX should be included for EI encounters too.  We revised the implementation guidance for this when we created the spec for CDM v3.1.

Implementation guidance is on iMeet here: https://pcornet.imeetcentral.com/p/aQAAAAAC4Zr4
