### ISSUE TITLE
Revise data type for PAYER_TYPE_PRIMARY and PAYER_TYPE_SECONDARY

### ISSUE THREAD

**Issue by smerek** [CDMFORUM/CDM-ERRATA#25]
Reported by Duke datamart: While preparing for the beta Diagnostic 4.0 we discovered that in the ENCOUNTER table the attribute PAYER_TYPE_PRIMARY and PAYER_TYPE_SECONDARY have data type RDBMS Text(4) and SAS CHAR (4) designated in the specification document, however the Pcornet PAYER_TYPE Value sets for this attribute contain codes with 5 characters.

Need to update datatype to RDBMS Text(5) and SAS Char(5).

**Comment by kmarsolo** [comment]
Resolved in v4.1
