### ISSUE TITLE
Spaces in the value set FACILITY_TYPE: "Code" column

### ISSUE THREAD

**Issue by ka156** [CDMFORUM/CDM-ERRATA#30]
Suggest removing spaces in the values in the "Code" column. 

Analysis by Sujung:

FACILITY_TYPE: there are space in the value(Code column). I listed all the row numbers of including space in the value. In the Excel, the row number will be the below number+1. For example, SPACE1=2 will be (2+1)=3rd row in the Excel file. 
 
 SPACE1=2 Y : 3rd row in the Excel AMBULANCE _BASED_CARE → there is a space between E and _
SPACE1=3 Y
SPACE1=11 Y
SPACE1=12 Y
SPACE1=13 Y
SPACE1=14 Y
SPACE1=15 Y
SPACE1=16 Y
SPACE1=17 Y
SPACE1=20 Y
SPACE1=22 Y
SPACE1=23 Y
SPACE1=24 Y
SPACE1=25 Y
SPACE1=26 Y
SPACE1=27 Y
SPACE1=28 Y
SPACE1=29 Y
SPACE1=30 Y
SPACE1=31 Y
SPACE1=32 Y
SPACE1=63 Y
SPACE1=79 Y

**Comment by kmarsolo** [comment]
Resolved in v1.4 of the value set reference file
