### ISSUE TITLE
Specimen Source: Placent -> placenta? 

### ISSUE THREAD

**Issue by Milanara** [CDMFORUM/CDM-ERRATA#32]
Wondering if placenta was accidentally made placent? I tried googling placent and can't find anything that seems right.

**Comment by kmarsolo** [comment]
Yes, that's a mistake on our part.  At this point, we don't want to have to push out another revision of the value set file, so if you have any placenta specimens in your source system, you can label them as "PLACENT" and then update the mapping once we revise the value set.

**Comment by smerek** [comment]
Corrected to "placenta" in version 1.5 of value set reference file.
