### ISSUE TITLE
Typo in PCORnet CDM v4.1 vauest file 1.4  -- "HOSPITA_AMBULATORY_SURGERY_FACILITY"

### ISSUE THREAD

**Issue by ka156** [CDMFORUM/CDM-ERRATA#36]
Typo in PCORnet CDM v4.1 vauest file 1.4, "FACILITY_TYPE" tab. In row 34 "HOSPITA_AMBULATORY_SURGERY_FACILITY" should be "HOSPITAL_AMBULATORY_SURGERY_FACILITY". 

Users are instructed to use the mis-spelled version at this time, and until it is corrected in the value set file. The PCORnet Code Errors query dose not examine this field.

**Comment by smerek** [comment]
Corrected in version 1.5 of value set reference file.
