### ISSUE TITLE
where did the CDM docs go???

### ISSUE THREAD

**Issue by dckc** [CDMFORUM/CDM-ERRATA#39]
The README for this repo says:

> Please note that the Common Data Model specifications are hosted at http://www.pcornet.org/pcornet-common-data-model/

but that link is broken. What's up?

I get:

Error 1016 Ray ID: 4ea17259ffda5f0b • 2019-06-20 23:15:46 UTC
Origin DNS error
What happened?

You've requested a page on a website (www.pcornet.org) that is on the Cloudflare network. Cloudflare is currently unable to resolve your requested domain (www.pcornet.org).

**Comment by ka156** [comment]
You can find links to the CDM document here: https://pcornet.org/data-driven-common-model/
Scroll to the bottom of the page to find the download links.
I will work to fix the README tomorrow, 6/21/19.

**Comment by dckc** [comment]
Please arrange for a redirect so that all the other such links around the
web will be restored.
