### ISSUE TITLE
ONSET_DATE definition

### ISSUE THREAD

**Issue by rusincovitch** [CDMFORUM/CDM-ERRATA#9]
A network has asked for clarification on the ONSET_DATE definition. Although the spec distinguishes it from REPORT_DATE, the differences are not described.

**Comment by rusincovitch** [comment]
I suggested that a reasonable working definition for CONDITION.ONSET_DATE would be:

The beginning date of the condition or disease state, which may be based on symptom onset or formal diagnosis, depending on the source data. This is a different concept than report date, which is the date on which the medical status was collected. For example, in the process of reviewing a medical history on January 1, 2016, a provider might record a condition of diabetes as **onset date** of March 1, 2014 (based on medical history), and **report date** of January 1, 2016.

**Comment by rusincovitch** [comment]
We will add to the agenda for the February 26 CONDITION interest group session for feedback.

**Comment by smerek** [comment]
Shelley, I like your proposed definition.  I searched "onset date" in the caDSR, and found the attached CDEs -- which may provide more food for thought!
[OnsetDate_CDEs.xlsx](https://github.com/CDMFORUM/CDM-ERRATA/files/105010/OnsetDate_CDEs.xlsx)

**Comment by rusincovitch** [comment]
Michelle, thank you - this is very helpful and seems a great basis for assessment!

I think my opinion of the best fit (from the potential 4 CDEs) is "The date and time when problem (illness, disorder, or symptom) started." But it will be good to see impressions from the interest group.

**Comment by rusincovitch** [comment]
This issue is being merged into the [guidance issue tracker](https://github.com/CDMFORUM/CDM-GUIDANCE/issues/1).
